"""
default_catalog.py — Static fallback task catalog for Evenly.

Used by catalog_agent.seed_default_catalog() when no CLAUDE_API_KEY is set,
or as the initial seed on first docker-compose up.

Field reference (matches TaskTemplate model):
  name                       str        concise, action-oriented
  description                str        1–2 sentences
  room_type                  str        kitchen|bathroom|bedroom|living|hallway|childrens_room|garden|other
  category                   str        cleaning|tidying|laundry|garden|decluttering|maintenance|other
  default_duration_minutes   int        5|10|15|20|30|45|60|90|120
  default_frequency_days     int        1|2|3|7|14|30|60|90|180|365
  energy_level               str        low|medium|high
  household_flag             str|None   children|cats|dogs  (None = always visible)
  device_flag                str|None   robot_vacuum|robot_mop|dishwasher|washer|dryer|
                                        window_cleaner|steam_cleaner|robot_mower|irrigation
  is_robot_variant           bool
  robot_frequency_multiplier float|None  e.g. 0.4 → manual task 60% less often when device present

Visibility rule:
  household_flag set  → is_active=False  (activated via household settings)
  device_flag set     → is_active=False  (activated when device confirmed in setup)
  both None           → is_active=True
"""

DEFAULT_TASKS = [

    # ══════════════════════════════════════════════════════════════════════════
    # KITCHEN — 20 base tasks
    # ══════════════════════════════════════════════════════════════════════════

    {
        "name": "Wipe kitchen counters",
        "description": "Wipe down all countertops with a damp cloth and all-purpose cleaner. Remove crumbs and spills to prevent bacteria.",
        "room_type": "kitchen", "category": "cleaning",
        "default_duration_minutes": 10, "default_frequency_days": 2,
        "energy_level": "low",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Clean kitchen sink and tap",
        "description": "Scrub the sink basin, clean the tap and handles. Remove limescale and food residue.",
        "room_type": "kitchen", "category": "cleaning",
        "default_duration_minutes": 10, "default_frequency_days": 3,
        "energy_level": "low",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Clean sink strainer and drain",
        "description": "Remove and clean the sink strainer. Clear any debris from the drain to prevent blockages and odours.",
        "room_type": "kitchen", "category": "cleaning",
        "default_duration_minutes": 5, "default_frequency_days": 7,
        "energy_level": "low",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Wipe hob / stovetop",
        "description": "Clean the hob surface, burners, and surrounding area. Remove grease and food residue.",
        "room_type": "kitchen", "category": "cleaning",
        "default_duration_minutes": 15, "default_frequency_days": 7,
        "energy_level": "medium",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Clean oven interior",
        "description": "Remove racks and scrub the oven cavity. Use oven cleaner for baked-on grease. Replace racks when dry.",
        "room_type": "kitchen", "category": "cleaning",
        "default_duration_minutes": 45, "default_frequency_days": 30,
        "energy_level": "high",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Clean oven door glass",
        "description": "Wipe down the oven door glass inside and out using a degreaser. Improves visibility and hygiene.",
        "room_type": "kitchen", "category": "cleaning",
        "default_duration_minutes": 10, "default_frequency_days": 14,
        "energy_level": "low",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Clean microwave inside",
        "description": "Wipe down the interior of the microwave. Place a bowl of water and lemon juice inside first to loosen residue.",
        "room_type": "kitchen", "category": "cleaning",
        "default_duration_minutes": 10, "default_frequency_days": 7,
        "energy_level": "low",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Wipe kitchen cabinet fronts",
        "description": "Wipe down all cabinet door fronts and handles with a damp cloth. Pay attention to grease build-up near the cooker.",
        "room_type": "kitchen", "category": "cleaning",
        "default_duration_minutes": 20, "default_frequency_days": 14,
        "energy_level": "medium",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Wipe kitchen splashback",
        "description": "Clean the wall tiles or splashback behind the hob and sink. Remove grease and food splatter.",
        "room_type": "kitchen", "category": "cleaning",
        "default_duration_minutes": 10, "default_frequency_days": 14,
        "energy_level": "medium",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Clean extractor fan filter",
        "description": "Remove the extractor fan filter and degrease it in hot soapy water or the dishwasher. Dry before replacing.",
        "room_type": "kitchen", "category": "maintenance",
        "default_duration_minutes": 20, "default_frequency_days": 30,
        "energy_level": "medium",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Descale kettle",
        "description": "Fill with water and descaler solution, boil, then rinse thoroughly. Prevents limescale build-up.",
        "room_type": "kitchen", "category": "maintenance",
        "default_duration_minutes": 15, "default_frequency_days": 30,
        "energy_level": "low",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Clean fridge interior",
        "description": "Remove all items, wipe shelves and drawers with a food-safe cleaner. Check expiry dates while restocking.",
        "room_type": "kitchen", "category": "cleaning",
        "default_duration_minutes": 30, "default_frequency_days": 30,
        "energy_level": "medium",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Clean fridge seals",
        "description": "Wipe the rubber door seals with a damp cloth and mild detergent. Prevents mould growth and maintains energy efficiency.",
        "room_type": "kitchen", "category": "cleaning",
        "default_duration_minutes": 10, "default_frequency_days": 30,
        "energy_level": "low",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Tidy pantry / food cupboard",
        "description": "Remove items, check expiry dates, wipe shelves, and reorganise. Move items near expiry to the front.",
        "room_type": "kitchen", "category": "tidying",
        "default_duration_minutes": 20, "default_frequency_days": 30,
        "energy_level": "low",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Vacuum kitchen floor manually",
        "description": "Vacuum the kitchen floor, paying attention to corners and under appliances. Removes crumbs and debris.",
        "room_type": "kitchen", "category": "cleaning",
        "default_duration_minutes": 10, "default_frequency_days": 3,
        "energy_level": "low",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": 0.4,
    },
    {
        "name": "Run robot vacuum in kitchen",
        "description": "Send the robot vacuum to clean the kitchen floor. Clear any obstacles beforehand.",
        "room_type": "kitchen", "category": "cleaning",
        "default_duration_minutes": 5, "default_frequency_days": 3,
        "energy_level": "low",
        "household_flag": None, "device_flag": "robot_vacuum",
        "is_robot_variant": True, "robot_frequency_multiplier": None,
    },
    {
        "name": "Mop kitchen floor manually",
        "description": "Mop the kitchen floor with a suitable floor cleaner. Allow to dry before walking on it.",
        "room_type": "kitchen", "category": "cleaning",
        "default_duration_minutes": 15, "default_frequency_days": 7,
        "energy_level": "medium",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": 0.4,
    },
    {
        "name": "Run robot mop in kitchen",
        "description": "Send the robot mop to clean the kitchen floor. Fill water tank and set appropriate cleaning mode.",
        "room_type": "kitchen", "category": "cleaning",
        "default_duration_minutes": 5, "default_frequency_days": 7,
        "energy_level": "low",
        "household_flag": None, "device_flag": "robot_mop",
        "is_robot_variant": True, "robot_frequency_multiplier": None,
    },
    {
        "name": "Hand wash dishes",
        "description": "Wash up dishes, pots, pans, and utensils by hand. Dry and put away.",
        "room_type": "kitchen", "category": "cleaning",
        "default_duration_minutes": 15, "default_frequency_days": 1,
        "energy_level": "low",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Empty and clean dishwasher",
        "description": "Empty the clean dishwasher and wipe down the interior, filter, and door seal to prevent odours.",
        "room_type": "kitchen", "category": "cleaning",
        "default_duration_minutes": 10, "default_frequency_days": 2,
        "energy_level": "low",
        "household_flag": None, "device_flag": "dishwasher",
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },

    # ══════════════════════════════════════════════════════════════════════════
    # BATHROOM — 18 base tasks
    # ══════════════════════════════════════════════════════════════════════════

    {
        "name": "Clean toilet bowl",
        "description": "Apply toilet cleaner, scrub the bowl with a toilet brush, and flush. Clean under the rim thoroughly.",
        "room_type": "bathroom", "category": "cleaning",
        "default_duration_minutes": 10, "default_frequency_days": 7,
        "energy_level": "low",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Wipe toilet exterior",
        "description": "Wipe down the outside of the toilet including the seat, lid, cistern, and base with disinfectant.",
        "room_type": "bathroom", "category": "cleaning",
        "default_duration_minutes": 5, "default_frequency_days": 7,
        "energy_level": "low",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Clean bathroom sink and tap",
        "description": "Scrub the sink basin, clean tap and handles. Remove toothpaste residue, soap scum, and limescale.",
        "room_type": "bathroom", "category": "cleaning",
        "default_duration_minutes": 10, "default_frequency_days": 7,
        "energy_level": "low",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Clean shower cubicle",
        "description": "Scrub the shower walls, tray, and door. Remove soap scum, mould, and limescale from all surfaces.",
        "room_type": "bathroom", "category": "cleaning",
        "default_duration_minutes": 20, "default_frequency_days": 7,
        "energy_level": "medium",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Clean bath tub",
        "description": "Scrub the bath tub interior and taps with a suitable cleaner. Remove soap scum and limescale.",
        "room_type": "bathroom", "category": "cleaning",
        "default_duration_minutes": 15, "default_frequency_days": 7,
        "energy_level": "medium",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Descale shower head",
        "description": "Soak the shower head in descaling solution or white vinegar for 30 minutes, then rinse. Restores water pressure.",
        "room_type": "bathroom", "category": "maintenance",
        "default_duration_minutes": 10, "default_frequency_days": 30,
        "energy_level": "low",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Clean bathroom tiles and grout",
        "description": "Scrub the wall tiles and grout lines. Pay attention to mould spots. Rinse thoroughly.",
        "room_type": "bathroom", "category": "cleaning",
        "default_duration_minutes": 30, "default_frequency_days": 30,
        "energy_level": "high",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Steam clean bathroom tiles",
        "description": "Use the steam cleaner on bathroom tiles and grout. Kills bacteria and removes stubborn stains without chemicals.",
        "room_type": "bathroom", "category": "cleaning",
        "default_duration_minutes": 20, "default_frequency_days": 30,
        "energy_level": "medium",
        "household_flag": None, "device_flag": "steam_cleaner",
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Wipe bathroom mirror",
        "description": "Clean the mirror with glass cleaner and a microfibre cloth. Remove toothpaste spots and water marks.",
        "room_type": "bathroom", "category": "cleaning",
        "default_duration_minutes": 5, "default_frequency_days": 7,
        "energy_level": "low",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Replace bathroom towels",
        "description": "Swap out used bath towels for fresh ones. Place used towels in the laundry.",
        "room_type": "bathroom", "category": "laundry",
        "default_duration_minutes": 5, "default_frequency_days": 7,
        "energy_level": "low",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Tidy bathroom cabinet / shelf",
        "description": "Reorganise toiletries, check expiry dates, and discard empty products. Wipe shelves while empty.",
        "room_type": "bathroom", "category": "tidying",
        "default_duration_minutes": 15, "default_frequency_days": 30,
        "energy_level": "low",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Clean bathroom extractor fan",
        "description": "Remove the fan cover and clean dust and debris. Good airflow prevents condensation and mould.",
        "room_type": "bathroom", "category": "maintenance",
        "default_duration_minutes": 15, "default_frequency_days": 90,
        "energy_level": "low",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Empty bathroom bin",
        "description": "Empty the bathroom bin and replace the liner. Wipe the inside of the bin if needed.",
        "room_type": "bathroom", "category": "tidying",
        "default_duration_minutes": 5, "default_frequency_days": 7,
        "energy_level": "low",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Vacuum bathroom floor manually",
        "description": "Vacuum the bathroom floor to remove hair and dust before mopping.",
        "room_type": "bathroom", "category": "cleaning",
        "default_duration_minutes": 5, "default_frequency_days": 7,
        "energy_level": "low",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": 0.4,
    },
    {
        "name": "Run robot vacuum in bathroom",
        "description": "Send the robot vacuum to clean the bathroom floor. Ensure floor is clear of rugs and items.",
        "room_type": "bathroom", "category": "cleaning",
        "default_duration_minutes": 5, "default_frequency_days": 7,
        "energy_level": "low",
        "household_flag": None, "device_flag": "robot_vacuum",
        "is_robot_variant": True, "robot_frequency_multiplier": None,
    },
    {
        "name": "Mop bathroom floor manually",
        "description": "Mop the bathroom floor with a disinfectant floor cleaner. Rinse to avoid residue.",
        "room_type": "bathroom", "category": "cleaning",
        "default_duration_minutes": 10, "default_frequency_days": 7,
        "energy_level": "low",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": 0.4,
    },
    {
        "name": "Run robot mop in bathroom",
        "description": "Send the robot mop to clean the bathroom floor. Use disinfectant cleaning solution in the water tank.",
        "room_type": "bathroom", "category": "cleaning",
        "default_duration_minutes": 5, "default_frequency_days": 7,
        "energy_level": "low",
        "household_flag": None, "device_flag": "robot_mop",
        "is_robot_variant": True, "robot_frequency_multiplier": None,
    },
    {
        "name": "Clean bathroom with electric window cleaner",
        "description": "Use the electric window cleaner on the shower screen, mirror, and tiles. Removes water spots efficiently.",
        "room_type": "bathroom", "category": "cleaning",
        "default_duration_minutes": 10, "default_frequency_days": 14,
        "energy_level": "low",
        "household_flag": None, "device_flag": "window_cleaner",
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },

    # ══════════════════════════════════════════════════════════════════════════
    # BEDROOM — 16 base tasks
    # ══════════════════════════════════════════════════════════════════════════

    {
        "name": "Change bed sheets",
        "description": "Remove and wash all bed linen — sheets, pillowcases, and duvet cover. Replace with fresh linen.",
        "room_type": "bedroom", "category": "laundry",
        "default_duration_minutes": 15, "default_frequency_days": 14,
        "energy_level": "medium",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Dust bedroom surfaces",
        "description": "Dust bedside tables, wardrobe tops, window sills, and all furniture surfaces. Use a damp cloth to trap dust.",
        "room_type": "bedroom", "category": "cleaning",
        "default_duration_minutes": 15, "default_frequency_days": 7,
        "energy_level": "low",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Vacuum bedroom floor manually",
        "description": "Vacuum the bedroom floor thoroughly, including under the bed and in corners.",
        "room_type": "bedroom", "category": "cleaning",
        "default_duration_minutes": 10, "default_frequency_days": 7,
        "energy_level": "low",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": 0.4,
    },
    {
        "name": "Run robot vacuum in bedroom",
        "description": "Send the robot vacuum to clean the bedroom floor. Move cables and low-hanging items first.",
        "room_type": "bedroom", "category": "cleaning",
        "default_duration_minutes": 5, "default_frequency_days": 7,
        "energy_level": "low",
        "household_flag": None, "device_flag": "robot_vacuum",
        "is_robot_variant": True, "robot_frequency_multiplier": None,
    },
    {
        "name": "Mop bedroom floor manually",
        "description": "Mop hard bedroom floors with a suitable cleaner. Let dry fully before replacing rugs.",
        "room_type": "bedroom", "category": "cleaning",
        "default_duration_minutes": 10, "default_frequency_days": 14,
        "energy_level": "low",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": 0.4,
    },
    {
        "name": "Run robot mop in bedroom",
        "description": "Send the robot mop to clean the bedroom floor. Remove rugs beforehand.",
        "room_type": "bedroom", "category": "cleaning",
        "default_duration_minutes": 5, "default_frequency_days": 14,
        "energy_level": "low",
        "household_flag": None, "device_flag": "robot_mop",
        "is_robot_variant": True, "robot_frequency_multiplier": None,
    },
    {
        "name": "Air the bedroom",
        "description": "Open windows for at least 10 minutes to refresh the air, reduce humidity, and remove stale air.",
        "room_type": "bedroom", "category": "other",
        "default_duration_minutes": 5, "default_frequency_days": 2,
        "energy_level": "low",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Tidy wardrobe",
        "description": "Refold and reorganise clothes in the wardrobe. Return items to their correct place.",
        "room_type": "bedroom", "category": "tidying",
        "default_duration_minutes": 20, "default_frequency_days": 30,
        "energy_level": "low",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Declutter wardrobe",
        "description": "Go through clothes and set aside items to donate, sell, or discard. Helps maintain a manageable wardrobe.",
        "room_type": "bedroom", "category": "decluttering",
        "default_duration_minutes": 45, "default_frequency_days": 180,
        "energy_level": "medium",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Wash pillows",
        "description": "Wash pillows in the washing machine on a gentle cycle. Tumble dry on low heat to fluff them up.",
        "room_type": "bedroom", "category": "laundry",
        "default_duration_minutes": 10, "default_frequency_days": 90,
        "energy_level": "low",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Wash duvet",
        "description": "Wash the duvet in the washing machine or take it to a laundromat. Tumble dry with dryer balls.",
        "room_type": "bedroom", "category": "laundry",
        "default_duration_minutes": 15, "default_frequency_days": 180,
        "energy_level": "low",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Clean bedroom windows",
        "description": "Clean the inside of bedroom windows. Wipe the frame and sill at the same time.",
        "room_type": "bedroom", "category": "cleaning",
        "default_duration_minutes": 15, "default_frequency_days": 30,
        "energy_level": "low",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Clean bedroom windows with electric cleaner",
        "description": "Use the electric window cleaner on bedroom windows for a streak-free finish.",
        "room_type": "bedroom", "category": "cleaning",
        "default_duration_minutes": 10, "default_frequency_days": 30,
        "energy_level": "low",
        "household_flag": None, "device_flag": "window_cleaner",
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Flip or rotate mattress",
        "description": "Rotate or flip the mattress 180 degrees. Extends mattress life and prevents uneven wear.",
        "room_type": "bedroom", "category": "maintenance",
        "default_duration_minutes": 15, "default_frequency_days": 90,
        "energy_level": "high",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Vacuum mattress",
        "description": "Vacuum the mattress surface to remove dust mites, dead skin cells, and allergens.",
        "room_type": "bedroom", "category": "cleaning",
        "default_duration_minutes": 10, "default_frequency_days": 30,
        "energy_level": "low",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Wipe bedroom skirting boards",
        "description": "Wipe down the skirting boards with a damp cloth to remove dust and scuffs.",
        "room_type": "bedroom", "category": "cleaning",
        "default_duration_minutes": 10, "default_frequency_days": 30,
        "energy_level": "low",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },

    # ══════════════════════════════════════════════════════════════════════════
    # LIVING ROOM — 17 base tasks
    # ══════════════════════════════════════════════════════════════════════════

    {
        "name": "Vacuum living room floor manually",
        "description": "Vacuum all floor surfaces in the living room including under the sofa and around furniture.",
        "room_type": "living", "category": "cleaning",
        "default_duration_minutes": 15, "default_frequency_days": 7,
        "energy_level": "medium",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": 0.4,
    },
    {
        "name": "Run robot vacuum in living room",
        "description": "Send the robot vacuum to clean the living room floor. Move cables and smaller objects off the floor first.",
        "room_type": "living", "category": "cleaning",
        "default_duration_minutes": 5, "default_frequency_days": 7,
        "energy_level": "low",
        "household_flag": None, "device_flag": "robot_vacuum",
        "is_robot_variant": True, "robot_frequency_multiplier": None,
    },
    {
        "name": "Mop living room floor manually",
        "description": "Mop hard living room floors with a suitable cleaner. Move furniture if needed.",
        "room_type": "living", "category": "cleaning",
        "default_duration_minutes": 15, "default_frequency_days": 14,
        "energy_level": "medium",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": 0.4,
    },
    {
        "name": "Run robot mop in living room",
        "description": "Send the robot mop to clean the living room floor. Remove rugs and low furniture beforehand.",
        "room_type": "living", "category": "cleaning",
        "default_duration_minutes": 5, "default_frequency_days": 14,
        "energy_level": "low",
        "household_flag": None, "device_flag": "robot_mop",
        "is_robot_variant": True, "robot_frequency_multiplier": None,
    },
    {
        "name": "Dust living room surfaces",
        "description": "Dust all shelves, TV unit, picture frames, and surfaces. Work from high to low.",
        "room_type": "living", "category": "cleaning",
        "default_duration_minutes": 15, "default_frequency_days": 7,
        "energy_level": "low",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Wipe TV screen",
        "description": "Gently clean the TV screen with a microfibre cloth. Never use spray cleaners directly on the screen.",
        "room_type": "living", "category": "cleaning",
        "default_duration_minutes": 5, "default_frequency_days": 14,
        "energy_level": "low",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Tidy living room",
        "description": "Put away books, magazines, remote controls, and any clutter. Return items to their correct places.",
        "room_type": "living", "category": "tidying",
        "default_duration_minutes": 10, "default_frequency_days": 2,
        "energy_level": "low",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Vacuum sofa cushions and crevices",
        "description": "Remove cushions and vacuum the sofa surface and crevices. Finds lost items and removes crumbs.",
        "room_type": "living", "category": "cleaning",
        "default_duration_minutes": 10, "default_frequency_days": 14,
        "energy_level": "low",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Wash sofa cushion covers",
        "description": "Remove the covers from sofa cushions and wash them according to the care label.",
        "room_type": "living", "category": "laundry",
        "default_duration_minutes": 10, "default_frequency_days": 90,
        "energy_level": "low",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Clean living room windows",
        "description": "Clean the inside of living room windows using glass cleaner and a lint-free cloth.",
        "room_type": "living", "category": "cleaning",
        "default_duration_minutes": 15, "default_frequency_days": 30,
        "energy_level": "low",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Clean living room windows with electric cleaner",
        "description": "Use the electric window cleaner on living room windows and glass doors. Fast and streak-free.",
        "room_type": "living", "category": "cleaning",
        "default_duration_minutes": 10, "default_frequency_days": 30,
        "energy_level": "low",
        "household_flag": None, "device_flag": "window_cleaner",
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Wipe light switches and door handles",
        "description": "Wipe down light switches, door handles, and remote controls with a disinfectant wipe. High-touch surfaces.",
        "room_type": "living", "category": "cleaning",
        "default_duration_minutes": 5, "default_frequency_days": 7,
        "energy_level": "low",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Dust blinds or clean curtains",
        "description": "Wipe down horizontal blinds with a damp cloth, or wash fabric curtains according to the care label.",
        "room_type": "living", "category": "cleaning",
        "default_duration_minutes": 20, "default_frequency_days": 30,
        "energy_level": "medium",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Declutter living room shelves",
        "description": "Remove items from shelves and decide what to keep, donate, or discard. Wipe shelves before restocking.",
        "room_type": "living", "category": "decluttering",
        "default_duration_minutes": 30, "default_frequency_days": 90,
        "energy_level": "low",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Wipe living room skirting boards",
        "description": "Wipe skirting boards with a damp cloth to remove dust build-up.",
        "room_type": "living", "category": "cleaning",
        "default_duration_minutes": 10, "default_frequency_days": 30,
        "energy_level": "low",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Clean indoor plants",
        "description": "Wipe dust from large plant leaves with a damp cloth. Check soil moisture and water if needed.",
        "room_type": "living", "category": "other",
        "default_duration_minutes": 10, "default_frequency_days": 14,
        "energy_level": "low",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Vacuum rugs",
        "description": "Vacuum area rugs thoroughly on both sides. Rotate rugs periodically to ensure even wear.",
        "room_type": "living", "category": "cleaning",
        "default_duration_minutes": 15, "default_frequency_days": 7,
        "energy_level": "medium",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },

    # ══════════════════════════════════════════════════════════════════════════
    # HALLWAY — 13 base tasks
    # ══════════════════════════════════════════════════════════════════════════

    {
        "name": "Vacuum hallway floor manually",
        "description": "Vacuum the hallway floor, including the entrance mat. The hallway gets heavy foot traffic.",
        "room_type": "hallway", "category": "cleaning",
        "default_duration_minutes": 10, "default_frequency_days": 3,
        "energy_level": "low",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": 0.4,
    },
    {
        "name": "Run robot vacuum in hallway",
        "description": "Send the robot vacuum to clean the hallway. Clear shoes and bags from the floor first.",
        "room_type": "hallway", "category": "cleaning",
        "default_duration_minutes": 5, "default_frequency_days": 3,
        "energy_level": "low",
        "household_flag": None, "device_flag": "robot_vacuum",
        "is_robot_variant": True, "robot_frequency_multiplier": None,
    },
    {
        "name": "Mop hallway floor manually",
        "description": "Mop the hallway floor to remove dirt tracked in from outside. Use appropriate cleaner for floor type.",
        "room_type": "hallway", "category": "cleaning",
        "default_duration_minutes": 10, "default_frequency_days": 7,
        "energy_level": "low",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": 0.4,
    },
    {
        "name": "Run robot mop in hallway",
        "description": "Send the robot mop to clean the hallway floor. Clear footwear from the floor first.",
        "room_type": "hallway", "category": "cleaning",
        "default_duration_minutes": 5, "default_frequency_days": 7,
        "energy_level": "low",
        "household_flag": None, "device_flag": "robot_mop",
        "is_robot_variant": True, "robot_frequency_multiplier": None,
    },
    {
        "name": "Shake out entrance mat",
        "description": "Take the entrance mat outside and shake out dirt and debris. Prevents dirt being walked further into the home.",
        "room_type": "hallway", "category": "cleaning",
        "default_duration_minutes": 5, "default_frequency_days": 7,
        "energy_level": "low",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Tidy hallway (shoes, coats, bags)",
        "description": "Put away shoes in the shoe rack, hang coats, and clear the hallway of bags and clutter.",
        "room_type": "hallway", "category": "tidying",
        "default_duration_minutes": 5, "default_frequency_days": 2,
        "energy_level": "low",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Wipe hallway door and frame",
        "description": "Wipe the front door, door frame, and letterbox area inside and out. Removes fingerprints and scuffs.",
        "room_type": "hallway", "category": "cleaning",
        "default_duration_minutes": 10, "default_frequency_days": 14,
        "energy_level": "low",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Clean hallway mirror",
        "description": "Clean the hallway mirror with glass cleaner and a microfibre cloth for a streak-free finish.",
        "room_type": "hallway", "category": "cleaning",
        "default_duration_minutes": 5, "default_frequency_days": 14,
        "energy_level": "low",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Wipe hallway skirting boards",
        "description": "Wipe skirting boards in the hallway to remove scuffs and dust build-up from foot traffic.",
        "room_type": "hallway", "category": "cleaning",
        "default_duration_minutes": 10, "default_frequency_days": 14,
        "energy_level": "low",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Dust hallway light fitting",
        "description": "Dust the hallway ceiling light fitting and any wall lights using a long-handled duster.",
        "room_type": "hallway", "category": "cleaning",
        "default_duration_minutes": 5, "default_frequency_days": 30,
        "energy_level": "low",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Organise shoe storage",
        "description": "Sort the shoe rack or cabinet. Discard worn-out shoes and pair up any orphaned ones.",
        "room_type": "hallway", "category": "decluttering",
        "default_duration_minutes": 15, "default_frequency_days": 90,
        "energy_level": "low",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Clean hallway windows or glass panels",
        "description": "Clean any glass panels in the hallway, including side windows beside the front door.",
        "room_type": "hallway", "category": "cleaning",
        "default_duration_minutes": 10, "default_frequency_days": 14,
        "energy_level": "low",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Check and replace light bulbs",
        "description": "Check all light bulbs in the hallway and common areas. Replace any that have blown.",
        "room_type": "hallway", "category": "maintenance",
        "default_duration_minutes": 10, "default_frequency_days": 90,
        "energy_level": "low",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },

    # ══════════════════════════════════════════════════════════════════════════
    # OTHER (general home) — 12 base tasks
    # ══════════════════════════════════════════════════════════════════════════

    {
        "name": "Do a laundry load",
        "description": "Sort, load, and start the washing machine. Check pockets and sort by colour and fabric type.",
        "room_type": "other", "category": "laundry",
        "default_duration_minutes": 10, "default_frequency_days": 3,
        "energy_level": "low",
        "household_flag": None, "device_flag": "washer",
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Hang or dry laundry",
        "description": "Transfer laundry from the washing machine to the dryer or hang on an airer to dry.",
        "room_type": "other", "category": "laundry",
        "default_duration_minutes": 10, "default_frequency_days": 3,
        "energy_level": "low",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Transfer laundry to dryer",
        "description": "Move washed laundry from the washing machine into the dryer. Select appropriate heat setting.",
        "room_type": "other", "category": "laundry",
        "default_duration_minutes": 5, "default_frequency_days": 3,
        "energy_level": "low",
        "household_flag": None, "device_flag": "dryer",
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Fold and put away laundry",
        "description": "Fold dried laundry and put each item away in the correct drawer or wardrobe.",
        "room_type": "other", "category": "laundry",
        "default_duration_minutes": 15, "default_frequency_days": 3,
        "energy_level": "low",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Clean washing machine drum",
        "description": "Run a hot empty cycle with washing machine cleaner or white vinegar. Prevents odours and residue build-up.",
        "room_type": "other", "category": "maintenance",
        "default_duration_minutes": 10, "default_frequency_days": 30,
        "energy_level": "low",
        "household_flag": None, "device_flag": "washer",
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Clean dryer lint filter",
        "description": "Remove and clean the lint filter after every use. A clogged filter reduces efficiency and is a fire hazard.",
        "room_type": "other", "category": "maintenance",
        "default_duration_minutes": 5, "default_frequency_days": 3,
        "energy_level": "low",
        "household_flag": None, "device_flag": "dryer",
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Clean robot vacuum dustbin and filters",
        "description": "Empty the dustbin, clean the filter, and check the brush roll for tangled hair or debris.",
        "room_type": "other", "category": "maintenance",
        "default_duration_minutes": 10, "default_frequency_days": 7,
        "energy_level": "low",
        "household_flag": None, "device_flag": "robot_vacuum",
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Clean robot mop water tank and pads",
        "description": "Empty, rinse, and dry the water tank. Wash the mopping pads and allow to dry fully.",
        "room_type": "other", "category": "maintenance",
        "default_duration_minutes": 10, "default_frequency_days": 7,
        "energy_level": "low",
        "household_flag": None, "device_flag": "robot_mop",
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Take out bins",
        "description": "Empty the household bins into the outdoor bin for collection. Replace bin liners.",
        "room_type": "other", "category": "other",
        "default_duration_minutes": 10, "default_frequency_days": 7,
        "energy_level": "low",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Wipe down general surfaces (high-touch)",
        "description": "Disinfect commonly-touched surfaces throughout the home: banister, light switches, remote controls, door handles.",
        "room_type": "other", "category": "cleaning",
        "default_duration_minutes": 10, "default_frequency_days": 7,
        "energy_level": "low",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Check smoke and CO detectors",
        "description": "Test the smoke and carbon monoxide detectors by pressing the test button. Replace batteries if needed.",
        "room_type": "other", "category": "maintenance",
        "default_duration_minutes": 5, "default_frequency_days": 180,
        "energy_level": "low",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Declutter junk drawer or storage box",
        "description": "Sort through miscellaneous drawers or storage boxes. Discard items that are no longer needed.",
        "room_type": "other", "category": "decluttering",
        "default_duration_minutes": 20, "default_frequency_days": 90,
        "energy_level": "low",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },

    # ══════════════════════════════════════════════════════════════════════════
    # GARDEN — 12 tasks
    # ══════════════════════════════════════════════════════════════════════════

    {
        "name": "Mow lawn manually",
        "description": "Mow the lawn to an appropriate height. Rake up clippings and compost or bag them.",
        "room_type": "garden", "category": "garden",
        "default_duration_minutes": 45, "default_frequency_days": 14,
        "energy_level": "high",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": 0.5,
    },
    {
        "name": "Run robot lawn mower",
        "description": "Start the robot lawn mower. Check boundary wire is intact and the area is clear of obstacles.",
        "room_type": "garden", "category": "garden",
        "default_duration_minutes": 10, "default_frequency_days": 7,
        "energy_level": "low",
        "household_flag": None, "device_flag": "robot_mower",
        "is_robot_variant": True, "robot_frequency_multiplier": None,
    },
    {
        "name": "Water garden plants manually",
        "description": "Water all garden beds, pots, and planters. Check soil moisture first to avoid overwatering.",
        "room_type": "garden", "category": "garden",
        "default_duration_minutes": 20, "default_frequency_days": 3,
        "energy_level": "low",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Check and run irrigation system",
        "description": "Inspect the irrigation system for blocked nozzles or leaks. Run a test cycle to confirm all zones work.",
        "room_type": "garden", "category": "maintenance",
        "default_duration_minutes": 15, "default_frequency_days": 14,
        "energy_level": "low",
        "household_flag": None, "device_flag": "irrigation",
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Weed garden beds",
        "description": "Remove weeds from garden beds by hand or with a hoe, ensuring roots are removed.",
        "room_type": "garden", "category": "garden",
        "default_duration_minutes": 30, "default_frequency_days": 14,
        "energy_level": "high",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Trim and edge lawn",
        "description": "Trim grass along path edges, flower bed borders, and fence lines using shears or an edger.",
        "room_type": "garden", "category": "garden",
        "default_duration_minutes": 20, "default_frequency_days": 14,
        "energy_level": "medium",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Prune shrubs and hedges",
        "description": "Trim overgrown shrubs and hedges. Dispose of trimmings in compost or garden waste bag.",
        "room_type": "garden", "category": "garden",
        "default_duration_minutes": 60, "default_frequency_days": 30,
        "energy_level": "high",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Sweep patio or decking",
        "description": "Sweep leaves, dirt, and debris from the patio, decking, or paths using a stiff broom.",
        "room_type": "garden", "category": "cleaning",
        "default_duration_minutes": 15, "default_frequency_days": 7,
        "energy_level": "low",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Clean garden furniture",
        "description": "Wipe down outdoor furniture with a damp cloth and mild detergent. Store cushions if rain is expected.",
        "room_type": "garden", "category": "cleaning",
        "default_duration_minutes": 20, "default_frequency_days": 14,
        "energy_level": "low",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Clear gutters",
        "description": "Remove leaves and debris from gutters and downpipes. Flush with water to ensure free flow.",
        "room_type": "garden", "category": "maintenance",
        "default_duration_minutes": 45, "default_frequency_days": 90,
        "energy_level": "high",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Add to compost bin",
        "description": "Add kitchen and garden waste to the compost bin. Turn the compost with a fork to aerate.",
        "room_type": "garden", "category": "garden",
        "default_duration_minutes": 10, "default_frequency_days": 7,
        "energy_level": "low",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Clean garden tools",
        "description": "Rinse soil from garden tools and dry thoroughly before storing. Apply light oil to metal parts to prevent rust.",
        "room_type": "garden", "category": "maintenance",
        "default_duration_minutes": 15, "default_frequency_days": 30,
        "energy_level": "low",
        "household_flag": None, "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },

    # ══════════════════════════════════════════════════════════════════════════
    # CHILDREN'S ROOM — 12 tasks (household_flag = "children")
    # ══════════════════════════════════════════════════════════════════════════

    {
        "name": "Change children's bed sheets",
        "description": "Remove and wash all bed linen from the children's bed. Replace with fresh, clean linen.",
        "room_type": "childrens_room", "category": "laundry",
        "default_duration_minutes": 15, "default_frequency_days": 7,
        "energy_level": "medium",
        "household_flag": "children", "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Sanitize baby changing mat",
        "description": "Wipe down the changing mat with a baby-safe disinfectant after every use, and deep clean weekly.",
        "room_type": "childrens_room", "category": "cleaning",
        "default_duration_minutes": 5, "default_frequency_days": 1,
        "energy_level": "low",
        "household_flag": "children", "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Clean highchair",
        "description": "Remove the tray and wipe all surfaces of the highchair with a food-safe cleaner. Check harness straps.",
        "room_type": "childrens_room", "category": "cleaning",
        "default_duration_minutes": 10, "default_frequency_days": 3,
        "energy_level": "low",
        "household_flag": "children", "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Disinfect teething toys and dummies",
        "description": "Sterilise teething toys, dummies, and small chewable objects using sterilising solution or steam steriliser.",
        "room_type": "childrens_room", "category": "cleaning",
        "default_duration_minutes": 10, "default_frequency_days": 3,
        "energy_level": "low",
        "household_flag": "children", "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Clean play mat",
        "description": "Wipe down foam or vinyl play mats with a baby-safe cleaner. Check for any tears or damage.",
        "room_type": "childrens_room", "category": "cleaning",
        "default_duration_minutes": 10, "default_frequency_days": 7,
        "energy_level": "low",
        "household_flag": "children", "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Sort toy storage",
        "description": "Return toys to their correct bins or shelves. Check for broken or missing parts and discard if unsafe.",
        "room_type": "childrens_room", "category": "tidying",
        "default_duration_minutes": 15, "default_frequency_days": 7,
        "energy_level": "low",
        "household_flag": "children", "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Wash children's soft toys",
        "description": "Machine wash or hand wash soft toys and stuffed animals according to their care label.",
        "room_type": "childrens_room", "category": "laundry",
        "default_duration_minutes": 10, "default_frequency_days": 30,
        "energy_level": "low",
        "household_flag": "children", "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Declutter outgrown clothes",
        "description": "Go through the child's wardrobe and set aside clothes that no longer fit for donating or storing.",
        "room_type": "childrens_room", "category": "decluttering",
        "default_duration_minutes": 30, "default_frequency_days": 90,
        "energy_level": "low",
        "household_flag": "children", "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Vacuum children's room floor",
        "description": "Vacuum the floor in the children's room, especially around play areas. Removes small parts and debris.",
        "room_type": "childrens_room", "category": "cleaning",
        "default_duration_minutes": 10, "default_frequency_days": 3,
        "energy_level": "low",
        "household_flag": "children", "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Wipe children's room surfaces",
        "description": "Wipe down all surfaces in the children's room including the changing table, shelves, and toy boxes.",
        "room_type": "childrens_room", "category": "cleaning",
        "default_duration_minutes": 10, "default_frequency_days": 7,
        "energy_level": "low",
        "household_flag": "children", "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Check baby monitor and safety equipment",
        "description": "Test the baby monitor, socket covers, and any safety gates. Replace batteries if needed.",
        "room_type": "childrens_room", "category": "maintenance",
        "default_duration_minutes": 10, "default_frequency_days": 30,
        "energy_level": "low",
        "household_flag": "children", "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Wash cot or crib bedding",
        "description": "Remove and wash the cot mattress cover, fitted sheet, and any blankets. Air the mattress while washing.",
        "room_type": "childrens_room", "category": "laundry",
        "default_duration_minutes": 10, "default_frequency_days": 7,
        "energy_level": "low",
        "household_flag": "children", "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },

    # ══════════════════════════════════════════════════════════════════════════
    # CATS — 8 tasks (household_flag = "cats")
    # ══════════════════════════════════════════════════════════════════════════

    {
        "name": "Clean litter box",
        "description": "Scoop out waste and clumps from the litter box. Dispose of waste hygienically.",
        "room_type": "other", "category": "cleaning",
        "default_duration_minutes": 5, "default_frequency_days": 1,
        "energy_level": "low",
        "household_flag": "cats", "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Deep clean litter box",
        "description": "Empty the litter box completely, wash with hot soapy water, rinse and dry, then refill with fresh litter.",
        "room_type": "other", "category": "cleaning",
        "default_duration_minutes": 15, "default_frequency_days": 7,
        "energy_level": "medium",
        "household_flag": "cats", "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Wash cat food and water bowls",
        "description": "Wash the cat's food and water bowls daily with hot soapy water. Refill with fresh water.",
        "room_type": "other", "category": "cleaning",
        "default_duration_minutes": 5, "default_frequency_days": 1,
        "energy_level": "low",
        "household_flag": "cats", "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Vacuum cat hair from upholstery",
        "description": "Use a lint roller or vacuum attachment to remove cat hair from sofa, chairs, and other soft furnishings.",
        "room_type": "living", "category": "cleaning",
        "default_duration_minutes": 10, "default_frequency_days": 3,
        "energy_level": "low",
        "household_flag": "cats", "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Clean and disinfect scratch post",
        "description": "Wipe down the scratch post base and surrounding area. Remove loose sisal fibres.",
        "room_type": "living", "category": "cleaning",
        "default_duration_minutes": 10, "default_frequency_days": 14,
        "energy_level": "low",
        "household_flag": "cats", "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Wash cat bed or blanket",
        "description": "Machine wash the cat's bed or blanket on a pet-safe cycle. Allow to dry fully before returning to the cat.",
        "room_type": "other", "category": "laundry",
        "default_duration_minutes": 10, "default_frequency_days": 14,
        "energy_level": "low",
        "household_flag": "cats", "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Check cat coat for parasites",
        "description": "Check the cat's coat for fleas, ticks, or other parasites. Comb through carefully with a flea comb.",
        "room_type": "other", "category": "other",
        "default_duration_minutes": 10, "default_frequency_days": 14,
        "energy_level": "low",
        "household_flag": "cats", "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Clean cat toys",
        "description": "Wash plastic or rubber cat toys in hot soapy water. Replace fabric toys that are worn or contaminated.",
        "room_type": "other", "category": "cleaning",
        "default_duration_minutes": 10, "default_frequency_days": 14,
        "energy_level": "low",
        "household_flag": "cats", "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },

    # ══════════════════════════════════════════════════════════════════════════
    # DOGS — 8 tasks (household_flag = "dogs")
    # ══════════════════════════════════════════════════════════════════════════

    {
        "name": "Wash dog bed",
        "description": "Wash the dog's bed cover and insert in the washing machine on a hot cycle. Tumble dry fully.",
        "room_type": "other", "category": "laundry",
        "default_duration_minutes": 10, "default_frequency_days": 14,
        "energy_level": "low",
        "household_flag": "dogs", "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Wash dog food and water bowls",
        "description": "Wash the dog's food and water bowls daily with hot soapy water. Refill with fresh water.",
        "room_type": "other", "category": "cleaning",
        "default_duration_minutes": 5, "default_frequency_days": 1,
        "energy_level": "low",
        "household_flag": "dogs", "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Vacuum dog hair from floors",
        "description": "Vacuum floors in areas where the dog spends most time. Use a pet hair attachment for best results.",
        "room_type": "other", "category": "cleaning",
        "default_duration_minutes": 15, "default_frequency_days": 2,
        "energy_level": "low",
        "household_flag": "dogs", "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Wipe paw prints from floor",
        "description": "Spot-mop dirty paw prints from hard floors near the entrance after walks.",
        "room_type": "hallway", "category": "cleaning",
        "default_duration_minutes": 5, "default_frequency_days": 2,
        "energy_level": "low",
        "household_flag": "dogs", "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Clean dog toys",
        "description": "Wash rubber and plastic dog toys in hot soapy water. Discard toys that are broken or heavily worn.",
        "room_type": "other", "category": "cleaning",
        "default_duration_minutes": 10, "default_frequency_days": 14,
        "energy_level": "low",
        "household_flag": "dogs", "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Check dog coat for parasites",
        "description": "Check the dog's coat and skin for fleas, ticks, or other parasites after outdoor activity.",
        "room_type": "other", "category": "other",
        "default_duration_minutes": 10, "default_frequency_days": 7,
        "energy_level": "low",
        "household_flag": "dogs", "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Vacuum dog hair from upholstery",
        "description": "Use a pet hair vacuum attachment or lint roller on sofas, chairs, and soft furnishings.",
        "room_type": "living", "category": "cleaning",
        "default_duration_minutes": 10, "default_frequency_days": 3,
        "energy_level": "low",
        "household_flag": "dogs", "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
    {
        "name": "Wipe down dog lead and collar",
        "description": "Wipe the dog's lead, collar, and harness with a pet-safe cleaning wipe. Check for wear and tear.",
        "room_type": "other", "category": "maintenance",
        "default_duration_minutes": 5, "default_frequency_days": 14,
        "energy_level": "low",
        "household_flag": "dogs", "device_flag": None,
        "is_robot_variant": False, "robot_frequency_multiplier": None,
    },
]
